### ISSUE TITLE
partitions not recognized on read from Windows from s3 parquet file

### ISSUE THREAD

**Issue by robertdavidwest** [dask/fastparquet#290]
I created a parquet hive file in a Unix environment with this code (this doesn't work on Windows, see [issue 289](https://github.com/dask/fastparquet/issues/289):
```
from fastparquet import write
import pandas as pd
import s3fs

s3 = s3fs.S3FileSystem()
bucket = "your-bucket-name"
filepath = "s3://{b}/testspace/example.parquet".format(b=bucket)
df = pd.DataFrame({'A': [1, 1, 2, 3], 'B': [4, 5, 6, 7]})

write(filepath,
    data=df,
    file_scheme='hive',
    object_encoding='bytes',
    partition_on=['A'],
    open_with=s3.open)
```
When I tried to read this file into a `ParquetFile` object on Windows the partitions are not recognized:

```
from fastparquet import ParquetFile
import s3fs

s3 = s3fs.S3FileSystem()
bucket = "your-bucket-name"
filepath = "s3://{b}/testspace/example.parquet".format(b=bucket)

pf = ParquetFile(filepath, open_with=s3.open)
print(pf)
```
yields:
```
<Parquet File: {u'rows': 4, u'name': 's3://bucket-name/testspace/example.parquet', u'columns': [u'A', u'B'], u'partitions': []}>
```
On unix:
```
<Parquet File: {u'rows': 4, u'name': u's3://bucket-name/testspace/example.parquet/_metadata', u'columns': [u'B'], u'partitions': [u'A']}>
```

`Windows OS: Microsoft Windows Server 2008`
`Nix: Linux 3.10.0-514.6.1.el7.x86_64 x86_64`
```
Python: 2.7
fastparquet: 0.1.3
pandas: 0.18.0
s3fs: 0.1.2
```

**Comment by martindurant** [comment]
This is fixed in master, soon to be released. For now, you need to provide the `sep='/'`  to `ParquetFile`, because by default it assumes that that os directory separator is used to mark directory names, on windows `r'\'`.

**Comment by robertdavidwest** [comment]
Great!! Thanks so much. I'll try that

**Comment by robertdavidwest** [comment]
`sep='/' ` worked perfectly for me in `ParquetFile`. Do you know if there is a way to feed this fix through `dask.dataframe.read_parquet`?

**Comment by robertdavidwest** [comment]
adding the `sep='/'` makes the partitions present in the meta data but when I apply `filters` its still not working:

```
pf=fastparquet.ParquetFile(filepath, open_with = s3.open, sep='/')
pf.to_pandas(filters=[('A', '==', 1)])
```

traceback:
```
ValueError                                Traceback (most recent call last)
<ipython-input-30-49e58f0e01bc> in <module>()
----> 1 pf.to_pandas(filters=[('A', '==', 1)])

C:\Anaconda\lib\site-packages\fastparquet\api.pyc in to_pandas(self, columns, categories, filters, index)
    404                          for (name, v) in views.items()}
    405                 self.read_row_group_file(rg, columns, categories, index,
--> 406                                          assign=parts)
    407                 start += rg.num_rows
    408         return df

C:\Anaconda\lib\site-packages\fastparquet\api.pyc in read_row_group_file(self, rg, columns, categories, index, assign)
    204                 fn, rg, columns, categories, self.schema, self.cats,
    205                 open=self.open, selfmade=self.selfmade, index=index,
--> 206                 assign=assign, scheme=self.file_scheme)
    207         if ret:
    208             return df

C:\Anaconda\lib\site-packages\fastparquet\core.pyc in read_row_group_file(fn, rg, columns, categories, schema_helper, cats, open, selfmade, index, assign, sep, scheme)
    282         return read_row_group(f, rg, columns, categories, schema_helper, cats,
    283                               selfmade=selfmade, index=index, assign=assign,
--> 284                               sep=sep, scheme=scheme)
    285
    286

C:\Anaconda\lib\site-packages\fastparquet\core.pyc in read_row_group(file, rg, columns, categories, schema_helper, cats, selfmade, index, assign, sep, scheme)
    342                 rg.columns[0].file_path.split(sep)[:-1])]
    343         val = val_to_num([p[1] for p in partitions if p[0] == cat][0])
--> 344         assign[cat][:] = cats[cat].index(val)
```

**Comment by martindurant** [comment]
Can you please check with the version in master?
(clone the repo or run `pip install git+https://github.com/dask/fastparquet`, ideally in a separate, non-critical environment)

**Comment by robertdavidwest** [comment]
sure, no problem

**Comment by robertdavidwest** [comment]
Ok. This works from `master`. I will eagerly await the next release. Thanks a lot.
